import '@/app/globals.css'
import NavBar from '@/components/NavBar'

export const metadata = {
  title: 'Users App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='h-screen'>
        <NavBar/>
        <main className='h-5/6'>
          {children}
        </main>
      </body>
    </html>
  )
}
